###
# Overwrite the Manifest.txt file with the actual contents of this directory
###
File.open("./Manifest.txt", 'w') { |file| file.puts Dir['**/*.*'] }

###
# Build the Gem
###
require 'rubygems'

gem 'hoe', '>= 2.1.0'
require 'hoe'
require File.dirname(__FILE__) + "/lib/advanced_math.rb"


Hoe.plugin :newgem # Hoe.plugin :website # Hoe.plugin :cucumberfeatures
$hoe = Hoe.spec 'advanced_math' do |p|
  p.developer('Glenn Nagel', 'glenn@mercury-wireless.com')
  p.remote_rdoc_dir = '' # Release to root only one project
  p.post_install_message = 'PostInstall.txt'
  p.extra_deps = []
  File.open(File.join(File.dirname(__FILE__), 'VERSION'), 'w') { |file| file.puts AdvancedMath::VERSION }
  # self.rubyforge_name = 'yourgemx' # if different than 'yourgem'
end

begin
  require 'jeweler'
  Jeweler::Tasks.new($hoe.spec)
rescue LoadError
  puts "Jeweler not available. Install it with: sudo gem install jeweler"
end

require 'newgem/tasks'
Dir['tasks/**/*.rake'].each { |t| load t }
remove_task :default
task :default => [:test]
