###
# Overwrite the Manifest.txt file with the actual contents of this directory
###
File.open("./Manifest.txt", 'w') { |file| file.puts Dir['**/*.*'] }

###
# Build the Gem
###
require 'rubygems'



gem 'hoe', '>= 2.1.0'
require 'hoe'
require 'fileutils'
require './lib/advanced_math'



Hoe.plugin :newgem
Hoe.plugin :website
# Hoe.plugin :cucumberfeatures

# Generate all the Rake tasks
# Run 'rake -T' to see list of generated tasks (from gem root directory)
$hoe = Hoe.spec 'adbanced_math' do
  self.developer 'Glenn Nagel', 'glenn@mercury-wireless.com'
  self.rubyforge_name       = self.name # TODO this is default value
end

require 'newgem/tasks'



Dir['tasks/**/*.rake'].each { |t| load t }
remove_task :default
task :default => [:test]
